/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SMSEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EXPIRY_SECONDS"
      | "POOL"
      | "USDC"
      | "claim"
      | "claimMessage"
      | "depositFor"
      | "escrows"
      | "getEscrow"
      | "isPoolRelayer"
      | "refund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Claimed" | "Deposited" | "Refunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EXPIRY_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "POOL", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMessage",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFor",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "EXPIRY_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "POOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPoolRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    claimToken: BytesLike,
    recipient: AddressLike,
    grossAmount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    claimToken: string,
    recipient: string,
    grossAmount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    claimToken: string;
    recipient: string;
    grossAmount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    claimToken: BytesLike,
    sender: AddressLike,
    amount: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    claimToken: string,
    sender: string,
    amount: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    claimToken: string;
    sender: string;
    amount: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    claimToken: BytesLike,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    claimToken: string,
    sender: string,
    amount: bigint
  ];
  export interface OutputObject {
    claimToken: string;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SMSEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): SMSEscrow;
  waitForDeployment(): Promise<this>;

  interface: SMSEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EXPIRY_SECONDS: TypedContractMethod<[], [bigint], "view">;

  POOL: TypedContractMethod<[], [string], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<
    [claimToken: BytesLike, recipientSig: BytesLike],
    [void],
    "nonpayable"
  >;

  claimMessage: TypedContractMethod<
    [claimToken: BytesLike, recipient: AddressLike],
    [string],
    "view"
  >;

  depositFor: TypedContractMethod<
    [claimToken: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        sender: string;
        amount: bigint;
        expiresAt: bigint;
        status: bigint;
        recipient: string;
      }
    ],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [claimToken: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        sender: string;
        amount: bigint;
        expiresAt: bigint;
        status: bigint;
        recipient: string;
      }
    ],
    "view"
  >;

  isPoolRelayer: TypedContractMethod<[], [boolean], "view">;

  refund: TypedContractMethod<[claimToken: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EXPIRY_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [claimToken: BytesLike, recipientSig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimMessage"
  ): TypedContractMethod<
    [claimToken: BytesLike, recipient: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositFor"
  ): TypedContractMethod<
    [claimToken: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        sender: string;
        amount: bigint;
        expiresAt: bigint;
        status: bigint;
        recipient: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [claimToken: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        sender: string;
        amount: bigint;
        expiresAt: bigint;
        status: bigint;
        recipient: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPoolRelayer"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[claimToken: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;

  filters: {
    "Claimed(bytes32,address,uint96,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Deposited(bytes32,address,uint96,uint64)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Refunded(bytes32,address,uint96)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
  };
}
