/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = { data: BytesLike; securityZone: BigNumberish };

export type InEuint128StructOutput = [data: string, securityZone: bigint] & {
  data: string;
  securityZone: bigint;
};

export interface Void402FacilitatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPaymentRequest"
      | "getPaymentRequest"
      | "paymentRequests"
      | "settlePayment"
      | "token"
      | "verifyPaymentRequest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentFailed"
      | "PaymentRequested"
      | "PaymentSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPaymentRequest",
    values: [BytesLike, AddressLike, InEuint128Struct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePayment",
    values: [BytesLike, InEuint128Struct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyPaymentRequest",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyPaymentRequest",
    data: BytesLike
  ): Result;
}

export namespace PaymentFailedEvent {
  export type InputTuple = [paymentId: BytesLike, reason: string];
  export type OutputTuple = [paymentId: string, reason: string];
  export interface OutputObject {
    paymentId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRequestedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    encryptedAmountHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    payee: string,
    encryptedAmountHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    payee: string;
    encryptedAmountHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSettledEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    encryptedAmountHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    payee: string,
    encryptedAmountHash: string
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    payee: string;
    encryptedAmountHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Void402Facilitator extends BaseContract {
  connect(runner?: ContractRunner | null): Void402Facilitator;
  waitForDeployment(): Promise<this>;

  interface: Void402FacilitatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPaymentRequest: TypedContractMethod<
    [
      paymentId: BytesLike,
      payee: AddressLike,
      encryptedAmount: InEuint128Struct,
      paymentHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getPaymentRequest: TypedContractMethod<
    [paymentId: BytesLike],
    [
      [string, string, bigint, boolean] & {
        payer: string;
        payee: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  paymentRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        payer: string;
        payee: string;
        encryptedAmount: bigint;
        paymentHash: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  settlePayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      encryptedAmount: InEuint128Struct,
      paymentHash: BytesLike
    ],
    [[boolean, bigint]],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  verifyPaymentRequest: TypedContractMethod<
    [paymentId: BytesLike],
    [
      [boolean, boolean, string] & {
        exists: boolean;
        settled: boolean;
        payee: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPaymentRequest"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      payee: AddressLike,
      encryptedAmount: InEuint128Struct,
      paymentHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPaymentRequest"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [
      [string, string, bigint, boolean] & {
        payer: string;
        payee: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        payer: string;
        payee: string;
        encryptedAmount: bigint;
        paymentHash: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "settlePayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      encryptedAmount: InEuint128Struct,
      paymentHash: BytesLike
    ],
    [[boolean, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyPaymentRequest"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [
      [boolean, boolean, string] & {
        exists: boolean;
        settled: boolean;
        payee: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PaymentFailed"
  ): TypedContractEvent<
    PaymentFailedEvent.InputTuple,
    PaymentFailedEvent.OutputTuple,
    PaymentFailedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRequested"
  ): TypedContractEvent<
    PaymentRequestedEvent.InputTuple,
    PaymentRequestedEvent.OutputTuple,
    PaymentRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSettled"
  ): TypedContractEvent<
    PaymentSettledEvent.InputTuple,
    PaymentSettledEvent.OutputTuple,
    PaymentSettledEvent.OutputObject
  >;

  filters: {
    "PaymentFailed(bytes32,string)": TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;
    PaymentFailed: TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;

    "PaymentRequested(bytes32,address,address,bytes32,uint256)": TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;
    PaymentRequested: TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;

    "PaymentSettled(bytes32,address,address,bytes32)": TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
    PaymentSettled: TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
  };
}
