/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = { data: BytesLike; securityZone: BigNumberish };

export type InEuint128StructOutput = [data: string, securityZone: bigint] & {
  data: string;
  securityZone: bigint;
};

export type PermissionStruct = { publicKey: BytesLike; signature: BytesLike };

export type PermissionStructOutput = [publicKey: string, signature: string] & {
  publicKey: string;
  signature: string;
};

export interface VoidFHERC20Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "balanceOf"
      | "decimals"
      | "eip712Domain"
      | "encryptedApprove"
      | "encryptedTransfer"
      | "encryptedTransferFrom"
      | "getEncryptedAllowance"
      | "getEncryptedBalance"
      | "getPrivacyLevel"
      | "name"
      | "privacyLevels"
      | "setPrivacyLevel"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "EIP712DomainChanged"
      | "EncryptedTransfer"
      | "PrivacyLevelUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedApprove",
    values: [AddressLike, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedTransfer",
    values: [AddressLike, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedTransferFrom",
    values: [AddressLike, AddressLike, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAllowance",
    values: [AddressLike, AddressLike, PermissionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike, PermissionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrivacyLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "privacyLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrivacyLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedApprove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrivacyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privacyLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrivacyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    encryptedAmount: BytesLike,
    privacyLevel: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    encryptedAmount: string,
    privacyLevel: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    encryptedAmount: string;
    privacyLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyLevelUpdatedEvent {
  export type InputTuple = [user: AddressLike, level: BigNumberish];
  export type OutputTuple = [user: string, level: bigint];
  export interface OutputObject {
    user: string;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VoidFHERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): VoidFHERC20;
  waitForDeployment(): Promise<this>;

  interface: VoidFHERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  encryptedApprove: TypedContractMethod<
    [spender: AddressLike, encryptedAmount: InEuint128Struct],
    [boolean],
    "nonpayable"
  >;

  encryptedTransfer: TypedContractMethod<
    [to: AddressLike, encryptedAmount: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  encryptedTransferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, encryptedAmount: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  getEncryptedAllowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike, permission: PermissionStruct],
    [string],
    "view"
  >;

  getEncryptedBalance: TypedContractMethod<
    [account: AddressLike, permission: PermissionStruct],
    [string],
    "view"
  >;

  getPrivacyLevel: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  privacyLevels: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setPrivacyLevel: TypedContractMethod<
    [level: BigNumberish],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "encryptedApprove"
  ): TypedContractMethod<
    [spender: AddressLike, encryptedAmount: InEuint128Struct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptedTransfer"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptedTransferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, encryptedAmount: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedAllowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike, permission: PermissionStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<
    [account: AddressLike, permission: PermissionStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrivacyLevel"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "privacyLevels"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setPrivacyLevel"
  ): TypedContractMethod<[level: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedTransfer"
  ): TypedContractEvent<
    EncryptedTransferEvent.InputTuple,
    EncryptedTransferEvent.OutputTuple,
    EncryptedTransferEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyLevelUpdated"
  ): TypedContractEvent<
    PrivacyLevelUpdatedEvent.InputTuple,
    PrivacyLevelUpdatedEvent.OutputTuple,
    PrivacyLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EncryptedTransfer(address,address,bytes32,uint8)": TypedContractEvent<
      EncryptedTransferEvent.InputTuple,
      EncryptedTransferEvent.OutputTuple,
      EncryptedTransferEvent.OutputObject
    >;
    EncryptedTransfer: TypedContractEvent<
      EncryptedTransferEvent.InputTuple,
      EncryptedTransferEvent.OutputTuple,
      EncryptedTransferEvent.OutputObject
    >;

    "PrivacyLevelUpdated(address,uint8)": TypedContractEvent<
      PrivacyLevelUpdatedEvent.InputTuple,
      PrivacyLevelUpdatedEvent.OutputTuple,
      PrivacyLevelUpdatedEvent.OutputObject
    >;
    PrivacyLevelUpdated: TypedContractEvent<
      PrivacyLevelUpdatedEvent.InputTuple,
      PrivacyLevelUpdatedEvent.OutputTuple,
      PrivacyLevelUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
