/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface X402PrivacyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRelayer"
      | "addSupportedToken"
      | "authorizedRelayers"
      | "deposit"
      | "externalTransfer"
      | "feeRecipient"
      | "getPoolInfo"
      | "getProofId"
      | "getProofInfo"
      | "getUserBalance"
      | "initRecipientBalance"
      | "internalTransfer"
      | "isRelayer"
      | "owner"
      | "poolMaintenanceFee"
      | "pools"
      | "proofs"
      | "removeRelayer"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "setPoolMaintenanceFee"
      | "setWithdrawFee"
      | "supportedTokens"
      | "transferOwnership"
      | "uploadProof"
      | "userBalances"
      | "withdraw"
      | "withdrawFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "ExternalTransfer"
      | "InternalTransfer"
      | "OwnershipTransferred"
      | "ProofUploaded"
      | "RelayerAdded"
      | "RelayerRemoved"
      | "TokenAdded"
      | "TokenRemoved"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRelayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "externalTransfer",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initRecipientBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "internalTransfer",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolMaintenanceFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "proofs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolMaintenanceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadProof",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "externalTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProofId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProofInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initRecipientBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRelayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolMaintenanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolMaintenanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExternalTransferEvent {
  export type InputTuple = [
    proofId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proofId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    proofId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InternalTransferEvent {
  export type InputTuple = [
    proofId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proofId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    proofId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofUploadedEvent {
  export type InputTuple = [
    proofId: BytesLike,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [proofId: string, sender: string, amount: bigint];
  export interface OutputObject {
    proofId: string;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerAddedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerRemovedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAddedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRemovedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402PrivacyPool extends BaseContract {
  connect(runner?: ContractRunner | null): X402PrivacyPool;
  waitForDeployment(): Promise<this>;

  interface: X402PrivacyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRelayer: TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;

  addSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedRelayers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  externalTransfer: TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getPoolInfo: TypedContractMethod<
    [token: AddressLike],
    [[bigint, boolean] & { totalDeposited: bigint; initialized: boolean }],
    "view"
  >;

  getProofId: TypedContractMethod<[nonce: BigNumberish], [string], "view">;

  getProofInfo: TypedContractMethod<
    [proofId: BytesLike],
    [
      [string, bigint, string, boolean, boolean] & {
        sender: string;
        amount: bigint;
        token: string;
        used: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getUserBalance: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        deposited: bigint;
        withdrawn: bigint;
      }
    ],
    "view"
  >;

  initRecipientBalance: TypedContractMethod<
    [recipient: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;

  internalTransfer: TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  isRelayer: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolMaintenanceFee: TypedContractMethod<[], [bigint], "view">;

  pools: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { totalDeposited: bigint; initialized: boolean }],
    "view"
  >;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        string,
        string,
        string
      ] & {
        sender: string;
        nonce: bigint;
        amount: bigint;
        token: string;
        used: boolean;
        initialized: boolean;
        proofBytes: string;
        commitmentBytes: string;
        blindingFactorBytes: string;
      }
    ],
    "view"
  >;

  removeRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPoolMaintenanceFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWithdrawFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uploadProof: TypedContractMethod<
    [
      nonce: BigNumberish,
      amount: BigNumberish,
      token: AddressLike,
      proofBytes: BytesLike,
      commitmentBytes: BytesLike,
      blindingFactorBytes: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userBalances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        available: bigint;
        deposited: bigint;
        withdrawn: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFee: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedRelayers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "externalTransfer"
  ): TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, boolean] & { totalDeposited: bigint; initialized: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofId"
  ): TypedContractMethod<[nonce: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getProofInfo"
  ): TypedContractMethod<
    [proofId: BytesLike],
    [
      [string, bigint, string, boolean, boolean] & {
        sender: string;
        amount: bigint;
        token: string;
        used: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        deposited: bigint;
        withdrawn: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initRecipientBalance"
  ): TypedContractMethod<
    [recipient: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "internalTransfer"
  ): TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isRelayer"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolMaintenanceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { totalDeposited: bigint; initialized: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        string,
        string,
        string
      ] & {
        sender: string;
        nonce: bigint;
        amount: bigint;
        token: string;
        used: boolean;
        initialized: boolean;
        proofBytes: string;
        commitmentBytes: string;
        blindingFactorBytes: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolMaintenanceFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWithdrawFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uploadProof"
  ): TypedContractMethod<
    [
      nonce: BigNumberish,
      amount: BigNumberish,
      token: AddressLike,
      proofBytes: BytesLike,
      commitmentBytes: BytesLike,
      blindingFactorBytes: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        available: bigint;
        deposited: bigint;
        withdrawn: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFee"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ExternalTransfer"
  ): TypedContractEvent<
    ExternalTransferEvent.InputTuple,
    ExternalTransferEvent.OutputTuple,
    ExternalTransferEvent.OutputObject
  >;
  getEvent(
    key: "InternalTransfer"
  ): TypedContractEvent<
    InternalTransferEvent.InputTuple,
    InternalTransferEvent.OutputTuple,
    InternalTransferEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofUploaded"
  ): TypedContractEvent<
    ProofUploadedEvent.InputTuple,
    ProofUploadedEvent.OutputTuple,
    ProofUploadedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerAdded"
  ): TypedContractEvent<
    RelayerAddedEvent.InputTuple,
    RelayerAddedEvent.OutputTuple,
    RelayerAddedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerRemoved"
  ): TypedContractEvent<
    RelayerRemovedEvent.InputTuple,
    RelayerRemovedEvent.OutputTuple,
    RelayerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAdded"
  ): TypedContractEvent<
    TokenAddedEvent.InputTuple,
    TokenAddedEvent.OutputTuple,
    TokenAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRemoved"
  ): TypedContractEvent<
    TokenRemovedEvent.InputTuple,
    TokenRemovedEvent.OutputTuple,
    TokenRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "Deposit(address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ExternalTransfer(bytes32,address,uint256)": TypedContractEvent<
      ExternalTransferEvent.InputTuple,
      ExternalTransferEvent.OutputTuple,
      ExternalTransferEvent.OutputObject
    >;
    ExternalTransfer: TypedContractEvent<
      ExternalTransferEvent.InputTuple,
      ExternalTransferEvent.OutputTuple,
      ExternalTransferEvent.OutputObject
    >;

    "InternalTransfer(bytes32,address,uint256)": TypedContractEvent<
      InternalTransferEvent.InputTuple,
      InternalTransferEvent.OutputTuple,
      InternalTransferEvent.OutputObject
    >;
    InternalTransfer: TypedContractEvent<
      InternalTransferEvent.InputTuple,
      InternalTransferEvent.OutputTuple,
      InternalTransferEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofUploaded(bytes32,address,uint256)": TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;
    ProofUploaded: TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;

    "RelayerAdded(address)": TypedContractEvent<
      RelayerAddedEvent.InputTuple,
      RelayerAddedEvent.OutputTuple,
      RelayerAddedEvent.OutputObject
    >;
    RelayerAdded: TypedContractEvent<
      RelayerAddedEvent.InputTuple,
      RelayerAddedEvent.OutputTuple,
      RelayerAddedEvent.OutputObject
    >;

    "RelayerRemoved(address)": TypedContractEvent<
      RelayerRemovedEvent.InputTuple,
      RelayerRemovedEvent.OutputTuple,
      RelayerRemovedEvent.OutputObject
    >;
    RelayerRemoved: TypedContractEvent<
      RelayerRemovedEvent.InputTuple,
      RelayerRemovedEvent.OutputTuple,
      RelayerRemovedEvent.OutputObject
    >;

    "TokenAdded(address)": TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;
    TokenAdded: TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;

    "TokenRemoved(address)": TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;
    TokenRemoved: TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;

    "Withdraw(address,address,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
