/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IERC8004IdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPassportId"
      | "isAgentRevoked"
      | "isAgentVerified"
      | "registerAgent"
      | "revokeAgent"
      | "updateMetadata"
      | "verifyAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentRevoked"
      | "AgentVerified"
      | "MetadataUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPassportId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentRevoked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentVerified",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPassportId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentRevoked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    operator: AddressLike,
    metadataURI: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    operator: string,
    metadataURI: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    operator: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVerifiedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, metadataURI: string];
  export type OutputTuple = [tokenId: bigint, metadataURI: string];
  export interface OutputObject {
    tokenId: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC8004Identity extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Identity;
  waitForDeployment(): Promise<this>;

  interface: IERC8004IdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPassportId: TypedContractMethod<[operator: AddressLike], [bigint], "view">;

  isAgentRevoked: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  isAgentVerified: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  revokeAgent: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMetadata: TypedContractMethod<
    [tokenId: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;

  verifyAgent: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPassportId"
  ): TypedContractMethod<[operator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAgentRevoked"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAgentVerified"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[metadataURI: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAgent"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVerified"
  ): TypedContractEvent<
    AgentVerifiedEvent.InputTuple,
    AgentVerifiedEvent.OutputTuple,
    AgentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentRevoked(uint256)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "AgentVerified(uint256)": TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;
    AgentVerified: TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;

    "MetadataUpdated(uint256,string)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
  };
}
