/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IX402PrivacyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "externalTransfer"
      | "getProofId"
      | "isRelayer"
      | "uploadProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "externalTransfer",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadProof",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "externalTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProofId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploadProof",
    data: BytesLike
  ): Result;
}

export interface IX402PrivacyPool extends BaseContract {
  connect(runner?: ContractRunner | null): IX402PrivacyPool;
  waitForDeployment(): Promise<this>;

  interface: IX402PrivacyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  externalTransfer: TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getProofId: TypedContractMethod<[nonce: BigNumberish], [string], "view">;

  isRelayer: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  uploadProof: TypedContractMethod<
    [
      nonce: BigNumberish,
      amount: BigNumberish,
      token: AddressLike,
      proofBytes: BytesLike,
      commitmentBytes: BytesLike,
      blindingFactorBytes: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "externalTransfer"
  ): TypedContractMethod<
    [proofId: BytesLike, recipient: AddressLike, relayerFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProofId"
  ): TypedContractMethod<[nonce: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isRelayer"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "uploadProof"
  ): TypedContractMethod<
    [
      nonce: BigNumberish,
      amount: BigNumberish,
      token: AddressLike,
      proofBytes: BytesLike,
      commitmentBytes: BytesLike,
      blindingFactorBytes: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
