/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC8004Reputation {
  export type ReputationStruct = {
    positiveSignals: BigNumberish;
    negativeSignals: BigNumberish;
    txCount: BigNumberish;
    totalVolume: BigNumberish;
    trustScore: BigNumberish;
  };

  export type ReputationStructOutput = [
    positiveSignals: bigint,
    negativeSignals: bigint,
    txCount: bigint,
    totalVolume: bigint,
    trustScore: bigint
  ] & {
    positiveSignals: bigint;
    negativeSignals: bigint;
    txCount: bigint;
    totalVolume: bigint;
    trustScore: bigint;
  };
}

export interface AgentReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReporter"
      | "authorizedReporters"
      | "getReputation"
      | "getTrustScore"
      | "identityRegistry"
      | "negativeSignals"
      | "owner"
      | "positiveSignals"
      | "postSignal"
      | "recordTransaction"
      | "removeReporter"
      | "renounceOwnership"
      | "totalVolume"
      | "transferOwnership"
      | "txCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReporterAdded"
      | "ReporterRemoved"
      | "SignalPosted"
      | "TransactionRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedReporters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "negativeSignals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positiveSignals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postSignal",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTransaction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "txCount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedReporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "negativeSignals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positiveSignals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postSignal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "txCount", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterAddedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterRemovedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalPostedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    positive: boolean,
    reason: string,
    reporter: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    positive: boolean,
    reason: string,
    reporter: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    positive: boolean;
    reason: string;
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionRecordedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    amountUSDC6Dec: BigNumberish,
    reporter: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    amountUSDC6Dec: bigint,
    reporter: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    amountUSDC6Dec: bigint;
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedReporters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getReputation: TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC8004Reputation.ReputationStructOutput],
    "view"
  >;

  getTrustScore: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  negativeSignals: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positiveSignals: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  postSignal: TypedContractMethod<
    [tokenId: BigNumberish, positive: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  recordTransaction: TypedContractMethod<
    [tokenId: BigNumberish, amountUSDC6Dec: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalVolume: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  txCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedReporters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC8004Reputation.ReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustScore"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "negativeSignals"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positiveSignals"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "postSignal"
  ): TypedContractMethod<
    [tokenId: BigNumberish, positive: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTransaction"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amountUSDC6Dec: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "txCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReporterAdded"
  ): TypedContractEvent<
    ReporterAddedEvent.InputTuple,
    ReporterAddedEvent.OutputTuple,
    ReporterAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterRemoved"
  ): TypedContractEvent<
    ReporterRemovedEvent.InputTuple,
    ReporterRemovedEvent.OutputTuple,
    ReporterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SignalPosted"
  ): TypedContractEvent<
    SignalPostedEvent.InputTuple,
    SignalPostedEvent.OutputTuple,
    SignalPostedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionRecorded"
  ): TypedContractEvent<
    TransactionRecordedEvent.InputTuple,
    TransactionRecordedEvent.OutputTuple,
    TransactionRecordedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReporterAdded(address)": TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;
    ReporterAdded: TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;

    "ReporterRemoved(address)": TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;
    ReporterRemoved: TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;

    "SignalPosted(uint256,bool,string,address)": TypedContractEvent<
      SignalPostedEvent.InputTuple,
      SignalPostedEvent.OutputTuple,
      SignalPostedEvent.OutputObject
    >;
    SignalPosted: TypedContractEvent<
      SignalPostedEvent.InputTuple,
      SignalPostedEvent.OutputTuple,
      SignalPostedEvent.OutputObject
    >;

    "TransactionRecorded(uint256,uint256,address)": TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
    TransactionRecorded: TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
  };
}
