/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentReputationRegistry } from "./AgentReputationRegistry";
export type { IAgentIdentityRegistry } from "./IAgentIdentityRegistry";
