/**
 * ZK Transfer Routes
 * Simplified API endpoints for private transfers (Stripe-like experience)
 */

import { Router, Request, Response } from 'express';
import { getZKProofService } from '../services/zkProofService.js';
import { getZKRelayerService } from '../services/zkRelayerService.js';
import { getZKBalanceService } from '../services/zkBalanceService.js';
import { getDatabaseService } from '../services/databaseService.js';
import { generatePrivacyNonce } from '../lib/zk-privacy-protection.js';
import { generalRateLimiter } from '../middleware/index.js';
import nacl from 'tweetnacl';
import bs58 from 'bs58';

const router = Router();

/**
 * POST /api/zk/transfer
 * Simplified transfer endpoint - handles proof upload and relayer submission
 * User just needs to sign a message to authorize
 */
router.post('/transfer', generalRateLimiter, async (req: Request, res: Response) => {
  try {
    const {
      sender_wallet,
      recipient,
      token,
      amount,
      wallet_signature,
      message_to_sign,
    } = req.body;

    // Validation
    if (!sender_wallet || !recipient || !token || !amount) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: sender_wallet, recipient, token, amount',
      });
    }

    if (!['SOL', 'USDC', 'USDT'].includes(token)) {
      return res.status(400).json({
        success: false,
        error: 'Token must be SOL, USDC, or USDT',
      });
    }

    if (amount <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Amount must be greater than zero',
      });
    }

    // Verify wallet signature
    if (!wallet_signature || !message_to_sign) {
      return res.status(400).json({
        success: false,
        error: 'Wallet signature required for authorization',
      });
    }

    try {
      const messageBytes = new TextEncoder().encode(message_to_sign);
      const signatureBytes = bs58.decode(wallet_signature);
      const publicKeyBytes = bs58.decode(sender_wallet);

      const isValid = nacl.sign.detached.verify(
        messageBytes,
        signatureBytes,
        publicKeyBytes
      );

      if (!isValid) {
        return res.status(401).json({
          success: false,
          error: 'Invalid wallet signature',
        });
      }
    } catch (sigError) {
      return res.status(401).json({
        success: false,
        error: 'Failed to verify wallet signature',
      });
    }

    // Check sender balance
    const balanceService = getZKBalanceService();
    const balance = await balanceService.getBalance(sender_wallet);

    if (!balance.success) {
      return res.status(500).json({
        success: false,
        error: 'Failed to check balance',
      });
    }

    const tokenBalance = token === 'SOL' ? balance.balances.sol :
                        token === 'USDC' ? balance.balances.usdc :
                        balance.balances.usdt;

    if (tokenBalance < amount) {
      return res.status(400).json({
        success: false,
        error: `Insufficient balance. Available: ${tokenBalance} ${token}`,
      });
    }

    // Generate privacy nonce
    const nonce = generatePrivacyNonce();

    // Create placeholder proof data (in production, this would be generated by ZK circuit)
    // For now, we use empty buffers and let the backend handle proof generation
    const proofBytes = Buffer.alloc(0);
    const commitmentBytes = Buffer.alloc(0);
    const blindingFactorBytes = Buffer.alloc(0);

    // Step 1: Upload proof (server-side signing)
    const proofService = getZKProofService();
    const uploadResult = await proofService.uploadProof({
      senderWallet: sender_wallet,
      token,
      amount,
      nonce,
      proofBytes,
      commitmentBytes,
      blindingFactorBytes,
      serverSign: true,
      walletSignature: wallet_signature,
      messageToSign: message_to_sign,
    });

    if (!uploadResult.success) {
      return res.status(500).json({
        success: false,
        error: `Failed to upload proof: ${uploadResult.error}`,
      });
    }

    // Step 2: Submit via relayer
    const relayerService = getZKRelayerService();
    const relayerResult = await relayerService.submitPayment({
      nonce,
      recipient,
      senderWallet: sender_wallet,
    });

    if (!relayerResult.success) {
      return res.status(500).json({
        success: false,
        error: `Failed to submit payment: ${relayerResult.error}`,
      });
    }

    // SECURITY: Log audit event
    const dbService = getDatabaseService();
    if (dbService.isAvailable()) {
      await dbService.logAuditEvent(
        'zk_transfer',
        sender_wallet,
        req.ip,
        req.get('user-agent'),
        {
          recipient,
          amount,
          token,
          nonce,
          signature: relayerResult.signature,
        }
      );
    }

    res.json({
      success: true,
      signature: relayerResult.signature,
      transfer_amount: relayerResult.transferAmount,
      proof_pda: uploadResult.proofPDA,
      nonce,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
  }
});

export default router;
