/**
 * ZK x402 Settle Routes (Simplified)
 * Simplified endpoint for settling x402 payments (Stripe-like experience)
 */

import { Router, Request, Response } from 'express';
import { getZKX402Service } from '../services/zkX402Service.js';
import { generalRateLimiter } from '../middleware/index.js';
import nacl from 'tweetnacl';
import bs58 from 'bs58';

const router = Router();

/**
 * POST /api/zk-x402/settle-simple
 * Simplified settle endpoint - user just signs a message to authorize
 */
router.post('/settle-simple', generalRateLimiter, async (req: Request, res: Response) => {
  try {
    const {
      paymentId,
      wallet,
      wallet_signature,
      message_to_sign,
    } = req.body;

    if (!paymentId || !wallet) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: paymentId, wallet',
      });
    }

    // Verify wallet signature if provided
    if (wallet_signature && message_to_sign) {
      try {
        const messageBytes = new TextEncoder().encode(message_to_sign);
        const signatureBytes = bs58.decode(wallet_signature);
        const publicKeyBytes = bs58.decode(wallet);

        const isValid = nacl.sign.detached.verify(
          messageBytes,
          signatureBytes,
          publicKeyBytes
        );

        if (!isValid) {
          return res.status(401).json({
            success: false,
            error: 'Invalid wallet signature',
          });
        }
      } catch (sigError) {
        return res.status(401).json({
          success: false,
          error: 'Failed to verify wallet signature',
        });
      }
    }

    const x402Service = getZKX402Service();
    
    // Get payment details
    const paymentResult = await x402Service.getPaymentStatus(paymentId);
    if (!paymentResult || !paymentResult.success || !paymentResult.payment) {
      return res.status(404).json({
        success: false,
        error: paymentResult?.error || 'Payment request not found',
      });
    }
    const payment = paymentResult.payment;

    if (payment.status !== 'pending') {
      return res.status(400).json({
        success: false,
        error: `Payment is already ${payment.status}`,
      });
    }

    // Create placeholder proof data (in production, this would be generated by ZK circuit)
    const proofBytes = Buffer.alloc(0);
    const commitmentBytes = Buffer.alloc(0);
    const blindingFactorBytes = Buffer.alloc(0);

    // Settle payment (backend handles proof upload and relayer)
    const result = await x402Service.settlePayment(
      paymentId,
      wallet,
      proofBytes,
      commitmentBytes,
      blindingFactorBytes,
      wallet_signature,
      message_to_sign
    );

    if (!result.success) {
      return res.status(500).json(result);
    }

    res.json({
      success: true,
      signature: result.signature,
      paymentId,
      message: 'Payment settled successfully',
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
  }
});

export default router;
