/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Precompiles,
  PrecompilesInterface,
} from "../../../../@fhenixprotocol/contracts/FheOS.sol/Precompiles";

const _abi = [
  {
    inputs: [],
    name: "Fheos",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60916037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806313d8d464146038575b600080fd5b603f608081565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220484c422a2a60ade38bef9380bbc074133bbea85689a97fe6a9b97c7ff746883164736f6c634300081c0033";

type PrecompilesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PrecompilesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Precompiles__factory extends ContractFactory {
  constructor(...args: PrecompilesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Precompiles & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Precompiles__factory {
    return super.connect(runner) as Precompiles__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PrecompilesInterface {
    return new Interface(_abi) as PrecompilesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Precompiles {
    return new Contract(address, _abi, runner) as unknown as Precompiles;
  }
}
