/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentIdentityRegistry,
  IAgentIdentityRegistryInterface,
} from "../../../contracts/AgentReputationRegistry.sol/IAgentIdentityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgentIdentityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentIdentityRegistryInterface {
    return new Interface(_abi) as IAgentIdentityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentIdentityRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAgentIdentityRegistry;
  }
}
