/**
 * Recent claim links generated by the connected wallet.
 *
 * Reads `Deposited` events from SMSEscrow on Base, filtered by the
 * connected sender wallet. No backend involved — chain is the source of
 * truth. Status (pending/claimed/refunded) is read per-row on demand;
 * here we just list the link with copy/open buttons.
 */

import { Icon } from "@iconify/react";
import { useEffect, useState } from "react";
import { useWallet } from "@/contexts/WalletContext";
import {
  SMS_ESCROW_ABI,
  SMS_ESCROW_ADDRESS,
  publicClient,
} from "@/lib/sms/contracts";

interface SmsHistoryCardProps {
  reloadTick: number;
}

interface LinkRow {
  claimToken: `0x${string}`;
  amount: string;
  blockNumber: number;
  txHash: `0x${string}`;
}

const BLOCK_WINDOW = 10000n; // ~5.5 hours on Base

const SmsHistoryCard = ({ reloadTick }: SmsHistoryCardProps) => {
  const { fullWalletAddress, isConnected } = useWallet();
  const [rows, setRows] = useState<LinkRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  useEffect(() => {
    if (!isConnected || !fullWalletAddress || !SMS_ESCROW_ADDRESS) {
      setRows([]);
      setLoading(false);
      return;
    }
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);

      // The user's wallet address might be checksum-cased; viem filters
      // indexed topics by the raw 32-byte left-padded form, so case
      // shouldn't matter, but pass lowercase to be safe.
      const senderLc = (fullWalletAddress as string).toLowerCase() as `0x${string}`;

      // Retry the event query — right after a fresh deposit the public RPC
      // node we hit may not yet have the latest block. Three quick attempts
      // covers nearly every propagation lag we see in practice.
      const delays = reloadTick > 0 ? [0, 1200, 2500, 5000] : [0];
      let mapped: LinkRow[] = [];
      let lastErr: unknown = null;
      for (const delay of delays) {
        if (delay > 0) await new Promise((r) => setTimeout(r, delay));
        if (cancelled) return;
        try {
          const latest = await publicClient.getBlockNumber();
          const fromBlock =
            latest > BLOCK_WINDOW ? latest - BLOCK_WINDOW : 0n;
          const events = await publicClient.getContractEvents({
            address: SMS_ESCROW_ADDRESS,
            abi: SMS_ESCROW_ABI as any,
            eventName: "Deposited",
            args: { sender: senderLc } as any,
            fromBlock,
            toBlock: "latest",
          } as any);
          mapped = (events as any[])
            .map((e) => ({
              claimToken: e.args.claimToken as `0x${string}`,
              amount: (Number(e.args.amount) / 1e6).toFixed(2),
              blockNumber: Number(e.blockNumber),
              txHash: e.transactionHash as `0x${string}`,
            }))
            .sort((a, b) => b.blockNumber - a.blockNumber)
            .slice(0, 25);
          if (mapped.length > 0 || reloadTick === 0) break;
        } catch (err) {
          lastErr = err;
        }
      }
      if (cancelled) return;
      if (mapped.length === 0 && lastErr) {
        setError(
          lastErr instanceof Error ? lastErr.message : String(lastErr)
        );
      }
      setRows(mapped);
      setLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [isConnected, fullWalletAddress, reloadTick]);

  async function copy(claimUrl: string, token: string) {
    try {
      await navigator.clipboard.writeText(claimUrl);
      setCopiedToken(token);
      setTimeout(() => setCopiedToken(null), 1500);
    } catch {
      // ignore
    }
  }

  return (
    <div
      className="w-full min-w-0 rounded-xl border p-4 sm:p-5 space-y-3"
      style={{
        borderColor: "var(--dash-border)",
        background: "var(--dash-overlay)",
      }}
    >
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex min-w-0 items-center gap-2">
          <Icon
            icon="ph:link-bold"
            className="h-4 w-4 shrink-0"
            style={{ color: "hsl(var(--beam-cyan))" }}
          />
          <h3
            className="truncate text-sm font-semibold"
            style={{ color: "var(--dash-text)" }}
          >
            Recent claim links
          </h3>
        </div>
        <span
          className="shrink-0 rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-widest"
          style={{
            borderColor: "var(--dash-border)",
            color: "var(--dash-text-muted)",
          }}
        >
          On-chain · last 5h
        </span>
      </div>

      {!isConnected && (
        <p className="text-xs" style={{ color: "var(--dash-text-faint)" }}>
          Connect a wallet to see the claim links you've generated.
        </p>
      )}

      {error && (
        <div
          className="text-xs break-words"
          style={{ color: "#ef4444" }}
        >
          {error}
        </div>
      )}

      {isConnected && loading && (
        <div
          className="flex items-center gap-2 text-xs"
          style={{ color: "var(--dash-text-muted)" }}
        >
          <Icon
            icon="ph:spinner-bold"
            className="h-3.5 w-3.5 animate-spin"
          />
          Reading chain…
        </div>
      )}

      {isConnected && !loading && !error && rows.length === 0 && (
        <p className="text-xs" style={{ color: "var(--dash-text-faint)" }}>
          You haven't generated any claim links in the last 5 hours.
        </p>
      )}

      {rows.length > 0 && (
        <ul className="space-y-2">
          {rows.map((r) => {
            const claimUrl =
              typeof window !== "undefined"
                ? `${window.location.origin}/claim/${r.claimToken}`
                : `/claim/${r.claimToken}`;
            return (
              <li
                key={r.claimToken}
                className="min-w-0 rounded-md border p-3"
                style={{
                  borderColor: "var(--dash-border)",
                  background: "var(--dash-surface)",
                }}
              >
                <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
                  <span
                    className="text-sm font-semibold"
                    style={{ color: "var(--dash-text)" }}
                  >
                    ${r.amount} USDC
                  </span>
                  <a
                    href={`https://basescan.org/tx/${r.txHash}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="shrink-0 text-[10px] underline underline-offset-2"
                    style={{ color: "var(--dash-text-faint)" }}
                  >
                    block {r.blockNumber}
                  </a>
                </div>
                <div
                  className="mt-1 font-mono text-[11px] break-all [overflow-wrap:anywhere]"
                  style={{ color: "var(--dash-text-muted)" }}
                >
                  {claimUrl}
                </div>
                <div className="mt-2 grid grid-cols-1 gap-2 sm:flex sm:flex-wrap sm:items-center">
                  <button
                    type="button"
                    onClick={() => copy(claimUrl, r.claimToken)}
                    className="inline-flex w-full items-center justify-center gap-1 rounded-md border px-2 py-1 text-[11px] sm:w-auto"
                    style={{
                      borderColor: "var(--dash-border)",
                      color: "var(--dash-text)",
                    }}
                  >
                    <Icon
                      icon={
                        copiedToken === r.claimToken
                          ? "ph:check-bold"
                          : "ph:copy-bold"
                      }
                      className="h-3 w-3 shrink-0"
                    />
                    <span className="truncate">
                      {copiedToken === r.claimToken ? "Copied" : "Copy link"}
                    </span>
                  </button>
                  <a
                    href={`/claim/${r.claimToken}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex w-full items-center justify-center gap-1 rounded-md border px-2 py-1 text-[11px] sm:w-auto"
                    style={{
                      borderColor: "var(--dash-border)",
                      color: "var(--dash-text)",
                    }}
                  >
                    <Icon
                      icon="ph:arrow-square-out-bold"
                      className="h-3 w-3 shrink-0"
                    />
                    <span className="truncate">Open claim page</span>
                  </a>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
};

export default SmsHistoryCard;
