/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TrustGatedTransfer,
  TrustGatedTransferInterface,
} from "../../contracts/TrustGatedTransfer";

const _abi = [
  {
    inputs: [],
    name: "AgentNotRegistered",
    type: "error",
  },
  {
    inputs: [],
    name: "AgentRevoked",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "score",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
    ],
    name: "InsufficientTrustScore",
    type: "error",
  },
  {
    inputs: [],
    name: "identityRegistry",
    outputs: [
      {
        internalType: "contract IERC8004Identity",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minimumTrustScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reputationRegistry",
    outputs: [
      {
        internalType: "contract IERC8004Reputation",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TrustGatedTransfer__factory {
  static readonly abi = _abi;
  static createInterface(): TrustGatedTransferInterface {
    return new Interface(_abi) as TrustGatedTransferInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TrustGatedTransfer {
    return new Contract(address, _abi, runner) as unknown as TrustGatedTransfer;
  }
}
